name: TypeSpec Compiler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile-typespec:
    name: Compile TypeSpec via Makefile
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install && npm install -g @typespec/compiler && npm install @typespec/protobuf

      # Step 4: Run Makefile
      - name: Run Makefile
        run: make all

      # Step 5: View Protofiles
      - name: View Protofiles
        run: ls tsp-output/@typespec/protobuf/resources

      # Step 6: Copy compiled proto files to desired directory
      - name: Sync Protobuf files
        run: |
          mkdir -p src/main/proto
          rm -rf node_modules
          cp -r tsp-output/@typespec/protobuf/resources/*.proto src/main/proto/

      # Step 7: Create a Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Sync updated proto files'
          branch: update-protos
          title: Update Protos
          body: |
            This PR updates the Protobuf files generated from the latest TypeSpec definitions.
